AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Parameters:
  roleArn:
    #Default: role
    Default: arn:aws:iam::084009911244:role/_visadmin
    Description: Role
    Type: String
  s3Bucket:
    #Default: s3Bucket
    Default: bigdatalabsvd
    Description: S3 bucket location for lambda code
    Type: String
  destinationArn:
    #Default: destinationArn
    Default: arn:aws:firehose:us-east-1:084009911244:deliverystream/kinesis1
    Description: Destination Arn such as kinesis, elasticsearch, s3
    Type: String
Resources:
  enablekinesissubscription:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri:
         Bucket: !Ref s3Bucket
         Key: enablesubscibe.zip
      Description: ''
      MemorySize: 128
      Timeout: 300
      Role: !Ref roleArn
      Events:
        CloudWatchEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              source:
                - aws.logs
              detail:
                eventSource:
                  - logs.amazonaws.com
                eventName:
                  - CreateLogGroup
      Environment:
        Variables:
          destinationArn: !Ref destinationArn
          roleArn: !Ref roleArn
